AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Utility functions for OHERO

Globals:
  Function:
    Architectures:
        # - x86_64
        - arm64

Resources:
  OpsAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/opsAgent/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          AWS_KB_ID: "string"
          BEDROCK_GUARDRAIL_ID: "string"
          BEDROCK_GUARDRAIL_VER: "string"
          EVENT_BUS_NAME: "string"
          EVENT_SOURCE_NAME: "string"
          KNOWLEDGE_BUCKET: "string"
          MEM_BUCKET: "string"
          OPS_KNOWLEDGE_BASE_ID: "string"
          SECHUB_KNOWLEDGE_BASE_ID: "string"
          TEAM_TABLE: "string"
          TICKET_TABLE: "string"

  SlackMeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/slackMe/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          SLACK_ACCESS_TOKEN: 'string'
          SLACK_CHANNEL_ID: 'string'

  SecHubReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/secHubReport/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          S3_NAME: ""

  SaveAccountInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/saveAccountInfo/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          S3_NAME: ""

  IngestOpsKbFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: handlers/ingestOpsKb/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          HEALTH_KNOWLEDGE_BASE_ID: "string"
          SECHUB_KNOWLEDGE_BASE_ID: "string"
          HEALTH_KB_DATA_SOURCE_ID: "string"
          SECHUB_KB_DATA_SOURCE_ID: "string"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints:
        - app.ts

  HandleSlackCommFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: handlers/handleSlackComm/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          SLACK_APP_VERIFICATION_TOKEN: 'string'
          SLACK_ACCESS_TOKEN: 'string'
          INTEGRATION_EVENT_BUS_NAME:  "string"
          EVENT_DOMAIN_PREFIX: "string"
          PAYLOAD_BUCKET: "string"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints:
        - app.ts

  CallbackEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: handlers/callbackEvent/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          CALLBACK_URL: ""
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints:
        - app.ts




