AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Utility functions for AiOps

Globals:
  Function:
    Architectures:
        # - x86_64
        - arm64

Resources:
  OpsAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/opsAgent/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          MEM_BUCKET: ""
          OPS_KNOWLEDGE_BASE_ID: ""
          SECHUB_KNOWLEDGE_BASE_ID: ""
          AWS_KB_ID: ""
          TICKET_TABLE: ""
          EVENT_SOURCE_NAME: ""
          BEDROCK_GUARDRAIL_ID: ""
          BEDROCK_GUARDRAIL_VER: ""

  SlackMeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/slackMe/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          SLACK_ACCESS_TOKEN: 'string'
          SLACK_CHANNEL_ID: 'string'

  SecHubReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/secHubReport/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          S3_NAME: ""

  IngestOpsKbFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: handlers/ingestOpsKb/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          HEALTH_KNOWLEDGE_BASE_ID: "string"
          SECHUB_KNOWLEDGE_BASE_ID: "string"
          HEALTH_KB_DATA_SOURCE_ID: "string"
          SECHUB_KB_DATA_SOURCE_ID: "string"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints:
        - app.ts

  EventToKnowledgeBaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: handlers/eventToKnowledgeBase/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          TARGET_S3_REGION: "string"
          OPS_HEALTH_S3: "string"
          TA_FINDINGS_s3: "string"
          SEC_FINDINGs_S3: "string"

  HandleSlackCommFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: handlers/handleSlackComm/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          SLACK_APP_VERIFICATION_TOKEN: 'string'
          SLACK_ACCESS_TOKEN: 'string'
          INTEGRATION_EVENT_BUS_NAME:  "string"
          EVENT_DOMAIN_PREFIX: "string"
          PAYLOAD_BUCKET: "string"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints:
        - app.ts

  CallbackEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: handlers/callbackEvent/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          CALLBACK_URL: ""
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints:
        - app.ts




